"""Rebuild only the four baselines in the requested paper-first, two-part structure."""
from pathlib import Path
import json, shutil
P=Path(__file__).resolve().parent
# Reuse layout/serialization helpers, without executing any old document generation.
ns={};prefix=(P/'build_series.py').read_text().split('# Ours keeps')[0]
prefix=prefix.replace("FONT='/tmp/ours_figure_NotoSansCJKsc-Regular.otf'", "FONT=str(OUT/'sources/diagram_font.otf')").replace("shutil.copyfile(FONT,OUT/'sources/diagram_font.otf')",'')
exec(prefix,ns)
Doc=ns['Doc'];E=ns['E']
_original_diagram=ns['diagram']
def plain_diagram(name,title,items,note,storage=False):
 mapping={'ᵤ':'_u','ᵥ':'_v','ₓ':'_x','₁':'1','₂':'2'}
 def clean(t):
  for a,b in mapping.items():t=t.replace(a,b)
  return t
 return _original_diagram(name,clean(title),[(clean(a),clean(b)) for a,b in items],clean(note),storage)
ns['diagram']=plain_diagram

def sub(self,t):self.xml.append(f'<h2>{E(t)}</h2>');self.md.append('### '+t)
def part(self,t):self.xml.append(f'<h1>{E(t)}</h1>');self.md.append('## '+t)
Doc.sub=sub;Doc.part=part
def storage(d):
 path=f'figures/{d.key}_storage.png';label='我们的磁盘实验：存储边界与读取顺序'
 d.xml.append(f'<img path="@./docs/analysis/disk_method_series_20260914/{path}" caption="{label}" width="1400"/>');d.md.append(f'![{label}]({path})')
def intro(key):
 item=next(i for i in json.loads((P/'manifest.json').read_text()) if i['key']==key)
 return Doc(key,item['title'],'第一部分按 SAQ 解读的顺序介绍论文原方法：全流程与符号 → 分步训练/编码 → 索引存储与查询 → 误差与边界。第二部分简述我们的磁盘实验改动和实际执行顺序。2026-09-15 调整结构；实验实现以此前核对的代码快照为依据，本次不运行新实验。')

# DiskANN
d=intro('02_diskann');d.part('第一部分：论文中的 DiskANN 方法')
d.sub('一、先看全流程与符号')
d.p('DiskANN 的主线是：先用 Vamana 建立可导航的稀疏图，再以 PQ 压缩数据库向量。查询时用内存中的 PQ 码估计邻居距离、选择扩展节点；访问 SSD 上该节点的原始向量与邻接表，并用精确距离维护最终结果。磁盘设计本身就是原论文的一部分。')
d.table(['符号','类型 / 含义'],[('N,D；x,q∈Rᴰ','库大小、维数；数据库向量、query'),('G；R；α','有向图；最大出度；robust pruning 松弛参数'),('Lbuild,L,W','建图搜索宽度；查询候选池容量；每轮扩展节点数'),('M,K；cₘⱼ；kₘ(x)','PQ 子空间数、中心数；子中心；存储的整数编号'),('Tₘ(j)；kout','query 到子中心的距离表；返回邻居数')])
d.fig('论文方法：Vamana 图、PQ 编码与 SSD 搜索',[('离线建立 Vamana','搜索邻居候选\nrobust prune + 反向边'),('训练 PQ 并编码','子空间聚类得到中心表\n每向量保存子中心编号'),('安排内存与 SSD','PQ codes 常驻内存\n原向量 + 邻接表在 SSD'),('query 准备 LUT','浮点 query 到各子中心\n一次建表、多次查表'),('BeamSearch 扩展','PQ 距离选 W 个节点\n批量读其磁盘记录'),('精确评分与返回','已读向量计算真实 L2\n维护精确 top-k 结果')], '本图仅解释论文方法；我们的码率设置、I/O 接口和缓存口径放在第二部分。')
d.sub('二、步骤 1：Vamana 搜索候选并选择邻接边')
d.p('输入是原始数据库向量与出度预算 R。论文先初始化图，再按顺序以每个数据库点 p 为 query，在当前图上运行 GreedySearch 获得候选；随后用 RobustPrune 选出至多 R 个邻居，加入反向边，对超出度数预算的邻接表再剪枝。输出是一份可供搜索的图，而不是每个点最接近的 R 个点的简单列表。')
d.p('RobustPrune 每次先选距 p 最近的候选 v，再从其余候选中移除可被 v 覆盖的点 u。用欧氏距离 δ 表示时，核心覆盖条件为：')
d.eq(r'\alpha\,\delta(v,u)\le\delta(p,u),\qquad\delta(a,b)=\|x_a-x_b\|_2.')
d.p('α=1 时更容易剪掉局部冗余边；增大 α 使条件更严格、保留更多连接机会，有助于形成长程导航。这里 α 作用在欧氏距离上；若用平方距离表达同一条件，左侧应是 α²δ²，不能混用。论文采用两遍构造，先 α=1，再用目标 α。建图距离基于全精度向量。')
d.sub('三、步骤 2：训练 PQ 码本并编码数据库')
d.p('把 D 维坐标分成 M 个子空间，在各子空间上聚类得到 K 个中心。编码一个 x 时，各子空间选择最近中心，只存中心编号。PQ 压缩的是子向量，不是为每个原始坐标独立选择一个标量刻度。')
d.eq(r'k_m(x)=\arg\min_{0\le j<K}\|x^{(m)}-c_{m,j}\|_2^2,\qquad \widetilde x=[c_{1,k_1(x)};\ldots;c_{M,k_M(x)}].')
d.eq(r'\mathrm{codebits}(x)=M\log_2K.')
d.p('例如 K=256、M=32 时，每个子码 1 字节，整向量编码 32 字节。这里 32 是子空间数，不是 32 bit/维。码本由全库共享，必须额外存储。PQ 码率越高通常重建误差越低，同时常驻内存与每候选查表次数增加。')
d.sub('四、步骤 3：索引真正存下什么')
d.table(['对象','论文中的位置 / 作用'],[('全库 PQ codes 与码本','内存；为任意新邻居提供便宜的距离估计'),('节点原始向量与邻接 ID','SSD 中共置；扩展节点时一并读取'),('热门节点记录','可选内存缓存；减少反复访问 SSD'),('候选池与查询 LUT','每 query 工作区；不属于共享数据库码')])
d.p('固定宽节点记录可以通过 ID 计算偏移；度数不足时填充。原向量随邻接表共置，目的是复用扩展操作已经发生的读取来做精确评分。论文用低维数据说明一条记录可以落在一个扇区；更高维或更大 R 时，记录可能跨多个扇区。')
d.sub('五、步骤 4：浮点 query 准备 ADC 查表')
d.eq(r'T_m(j)=\|q^{(m)}-c_{m,j}\|_2^2,\qquad \widehat d_{\rm PQ}^2(q,x)=\sum_m T_m(k_m(x)).')
d.p('输入是浮点 query 与共享码本；输出是 M 张距离表。之后每个候选只需读它的 PQ 编号并 lookup-add，无须重建完整 x。该式省略共享平移的等价记号，说明的是浮点 query 对数据库 PQ 码的非对称距离计算。')
d.sub('六、步骤 5：BeamSearch 与隐式重排')
d.p('查询从入口开始，候选池按 PQ 近似距离维护最多 L 个节点。每轮选最多 W 个尚未扩展的近候选，一起请求其 SSD 记录；读回后用邻接 ID 找到新节点，以内存 PQ 码评分并更新候选池。W 控制一次推进多少节点，L 控制保留多少搜索候选，两者不同。')
d.p('读取的原向量用于计算 d²(q,x)=Σⱼ(qⱼ−xⱼ)²，并维护精确结果。由于原向量与邻接表同读，不必末尾再随机取回所有候选原向量；论文称其为 implicit re-ranking。停止后从已精确评估的节点中返回 top-k。热门节点缓存还可进一步减少 I/O。')
d.sub('七、从误差看方法边界')
d.eq(r'e_x=\widetilde x-x,\qquad\widehat d_{\rm PQ}^2-d^2=-2(q-x)^\top e_x+\|e_x\|^2.')
d.p('PQ 误差会改变扩展优先级，有限 L 和图结构又决定访问集合。精确评分能修复已读节点之间的排序，无法找回未访问的近邻。增加 W 可能减少串行等待，也可能读入更多最终无用的节点；这需要在延迟、吞吐和 recall 之间取舍。')
d.source('原论文 §2、§3.1—3.5','DiskANN: Fast Accurate Billion-point Nearest Neighbor Search on a Single Node','https://harsha-simhadri.org/pubs/DiskANN19.pdf')
d.part('第二部分：我们的磁盘实验改了什么')
d.p('DiskANN 本来就是磁盘算法。我们的工作主要是把官方 Rust diskann-disk 接入统一实验框架，并固定输入、码率、缓存与计数口径。')
d.table(['项目','实验中的处理'],[('图与编码','复用 canonical shared graph；官方 PQ training/export；M=ceil(D/2)，每子码 8 bit'),('I/O 与缓存','官方 O_DIRECT + io_uring 路径及 completion 修复；C0 无跨 query 节点缓存，仍有 query 内页缓存'),('实验控制','固定数据划分、并发数、二进制哈希；记录实际请求和读取字节')])
storage(d)
d.p('实际顺序：query 建 LUT → 用内存 PQ 码维护候选池 → 选择展开节点 → 官方 reader 取节点页 → 更新邻居近似分数与当前节点精确结果 → 返回。D=1024 时 PQ 码为 512 字节/向量；FP32 原向量已占一页，加邻接表会超过一页。rerank_us=0 仅是计数口径，不表示没有精确评分。')
d.source('实现定位','experiments/05_disk_system_fair/native_diskann/src/main.rs；cached_reader.rs；query_cache.rs。已有 test 结果与正式验收状态保持原口径，本次不重测。');d.save()

# SymphonyQG
d=intro('03_symphonyqg');d.part('第一部分：论文中的 SymphonyQG 方法')
d.sub('一、先看全流程与符号')
d.p('SymphonyQG 把图结构、RaBitQ 编码和 FastScan 联合设计：对每个节点，以它自己为中心量化所有邻居，并将这些边码连续保存；搜索时批量估计邻居距离，同时利用当前节点的原向量做精确评分。理解顺序是先弄清一条边怎样编码，再看这些编码如何支撑建图、存储和查询。')
d.table(['符号','类型 / 含义'],[('xᵤ,xᵥ,q∈Rᴰ','当前节点、邻居向量和 query'),('T；d','共享正交/补维旋转；编码维数'),('zᵤᵥ=T(xᵥ−xᵤ)；nᵤᵥ','边残差及其模长'),('oᵤᵥ；sᵤᵥ；αᵤᵥ','单位残差、单位符号码方向、二者内积'),('R,L,kout','出度、候选池容量、最终结果数')])
d.fig('论文方法：边中心编码、连续行与多估计搜索',[('以节点为参考中心','对边 u→v 形成 xᵥ−xᵤ\n保留边长与方向信息'),('旋转与 RaBitQ 编码','单位方向 → 1-bit 码\n预计算比值修正因子'),('联合调整图结构','FastScan 搜索邻居候选\n剪枝、补边并更新边码'),('连续行组织','原向量 u + 所有邻居码\n边系数 + 邻接 ID'),('query LUT 批量估计','当前节点精确距离\nFastScan 估计邻居距离'),('多估计与隐式重排','未展开 v 可再次入池\n已展开节点维护精确结果')], '这是论文的内存访问流程；按 4 KiB 读盘与实验端口细节集中在第二部分。')
d.sub('二、步骤 1：以当前节点为中心，分离边长与方向')
d.eq(r'z_{uv}=T(x_v-x_u),\quad n_{uv}=\|x_v-x_u\|,\quad o_{uv}=z_{uv}/n_{uv},\quad y_u=T(q-x_u).')
d.eq(r'\|q-x_v\|^2=\|q-x_u\|^2+n_{uv}^2-2y_u^\top z_{uv}.')
d.p('输入是一条边 u→v。输出是邻居相对 u 的残差方向和真实边长。中心不是全库一个均值：同一 v 可以在不同父节点下拥有不同编码。这既是边码需要复制的原因，也是后面多次估计同一候选的基础。零长度边不使用单位化除法。')
d.sub('三、步骤 2：1-bit 方向码与比值修正')
d.eq(r's_{uv}=\operatorname{sign}(o_{uv})/\sqrt d,\quad \alpha_{uv}=o_{uv}^\top s_{uv},\quad t_{uv}=n_{uv}s_{uv}/\alpha_{uv}.')
d.eq(r'\widehat d_{uv}^2=\|q-x_u\|^2+n_{uv}^2-2y_u^\top t_{uv}.')
d.p('这是忽略 query 量化误差时的方向估计表达。实际保存符号 bit 与可预计算系数，查询不用显式构造 t。α 是方向内积；除以 α 修正尺度，不能误写成再改变码字方向。与 SAQ 示例的比值估计相似，保留真实模长后，只近似距离中的交叉内积。')
d.eq(r'z_{uv}^\top(t_{uv}-z_{uv})=0.')
d.p('该恒等式说明理想代数中的替代向量误差垂直于原边残差，不表示任意 query 的内积都准确。与全局数据库码不同，每条出边都需要自己的方向和因子。')
d.sub('四、步骤 3：FastScan 怎样批量计算内积')
d.xml.append((P/'fastscan_explainer/section.xml').read_text())
d.md.append((P/'fastscan_explainer/section.md').read_text())
d.sub('五、步骤 4：用量化搜索建图，并补齐批次')
d.p('论文先随机初始化图，再迭代：依据当前边生成编码，用上述搜索方法为每个节点发现候选，以 NSG 式几何规则剪枝，统一更新图。每轮内部不同节点的候选生成和剪枝可并行，轮末再切换到新图。最终邻接关系改变后重新生成匹配的边码。')
d.p('若节点度数小于目标 R，FastScan 的固定批次会出现无效槽。论文对已剪候选放宽角度阈值，补足邻居，使出度对齐 32 的倍数；极端不足时还有随机补边。它减少批内浪费，但新增边及其复制码仍然占用存储空间。')
d.sub('六、步骤 5：索引真正存下什么')
d.table(['每节点对象','作用 / 大致成本'],[('当前节点原向量','精确评分；约 4D 字节'),('R 个邻居的边局部符号码','连续 FastScan 扫描；约 Rd/8 字节'),('逐边预计算因子','边长、比值修正和中心相关项'),('邻接 ID','确定每个估计对应哪个节点；约 4R 字节')])
d.p('原论文将这些数据紧邻放在内存中的一个连续对象里。访问节点 u 时，一次顺序读取既支持对 u 精确评分，也支持估计所有邻居；不能把“每边每维 1 bit”解释为全库每向量只占 d/8 字节。码的复制程度与 R 有关。')
d.sub('七、步骤 6：多次估计与隐式重排')
d.p('query 完成共享准备后，从候选池弹出近似距离最小的未展开节点 u，标记已访问；用它的原向量计算精确距离并更新结果，再用 u 的连续边码批量评估邻居。尚未展开的 v 可以从不同父节点多次带着不同估计入池。只有已展开者被跳过，不能在首次发现时就永久去重。')
d.p('多个估计给近邻更多被优先展开的机会。论文用 RaBitQ 的统计误差性质解释这种机制；不同边的估计不应无条件当成相互独立。搜索结束时，从已经精确评分的节点返回结果，因此无需另做一轮普通的末尾原向量随机重排。')
d.sub('八、从误差看方法边界')
d.eq(r'\widehat d_{uv}^2-d^2(q,x_v)=-2y_u^\top(t_{uv}-z_{uv}).')
d.p('上式仅分析理想 query 下单次边估计；实际 query/LUT 量化还会增加计算误差。多估计和精确结果维护减少了部分排序错误，但没有排除有限池、图路径和未展开近邻造成的遗漏。连续内存访问的收益也不自动等于磁盘场景的收益。')
d.source('原论文','用户提供 SymphonyQG.pdf，§3.1—3.3、Algorithms 1—2；出版占位信息不作正式书目信息。')
d.part('第二部分：我们的磁盘实验改了什么')
d.p('将官方 QG 的连续节点行按 4 KiB 分页保存，保留 rotator、query LUT、FastScan、展开时去重及精确结果池；读取改为 O_DIRECT/libaio，加上每 query 的有界页缓存。')
storage(d)
d.p('实际顺序：准备 query → 弹出 u → 读 u 的整行 → 精确评估 u、批量估计其邻居 → 未展开邻居入池 → 输出精确结果。未决定展开的 v 不预读整行；若结果不足 k，则按官方补全规则读取邻居。当前使用 R=64、6-bit query；unsigned 扩展修复避免 FastScan 的大累加值被解释为负数。')
d.p('当前行长为 4D+Rd/8+12R+4R 字节。D=d=1024、R=64 时为 13312 字节，独占 4 页，共 16384 字节。这里新增的是页对齐及真实磁盘读取成本，不能用“一次节点访问”代替“一次 4 KiB I/O”。')
d.source('实现定位','experiments/05_disk_system_fair/native/symphonyqg_disk_port.cpp；baselines/symphonyqg/symqglib/qg/qg_query.hpp、qg_scanner.hpp。');d.save()

# LVQ
d=intro('04_og_lvq');d.part('第一部分：论文中的 LVQ 方法')
d.sub('一、先看全流程与符号')
d.p('LVQ 的全称是 Locally-adaptive Vector Quantization：先对数据库中心化，再对每个向量独立选择标量量化范围；第一层压缩码支撑图构建与遍历，可选第二层残差码用于最终重排。这里 local 指逐向量范围，不是局部 PQ 码本。依据的是 Similarity search in the blink of an eye with compressed indices。')
d.table(['符号','类型 / 含义'],[('x,q,c∈Rᴰ','数据库向量、浮点 query、数据库均值'),('rₓ=x−c；aₓ,bₓ','中心化向量；该向量坐标的最小值和最大值'),('B₁,Δₓ,kₓ','一级 bit 数、步长、整数标签向量'),('r̃ₓ,eₓ,êₓ；B₂','一级重建、其残差、残差重建；二级 bit 数'),('R,W,kout','图出度、候选池宽度、最终返回数')])
d.fig('论文方法：LVQ 一级编码与可选残差重排',[('数据库中心化','计算共享均值 c\n每个向量减同一个 c'),('逐向量定量化区间','aₓ=min rₓ，bₓ=max rₓ\n生成一级整数标签'),('可选二级残差编码','eₓ=rₓ−一级重建\n范围由一级步长决定'),('构建并保存图索引','LVQ 压缩向量参与构图\n保存图、主码和可选残差'),('一级码引导搜索','浮点 query 对重建值评分\n维护有限宽候选池'),('可选二级重排','取候选对应残差码\n用两层重建距离选 top-k')], '论文包含单层与双层版本；我们实际采用的单层 LVQ4 放在第二部分说明。')
d.sub('二、步骤 1：减均值，使各维偏移更一致')
d.eq(r'c=\frac1N\sum_xx,\qquad r_x=x-c,\qquad r_q=q-c.')
d.p('输入是数据库向量，输出是共享均值与中心化向量。减均值本身保持两点 L2，不损失信息；它降低各维固定偏移对范围的影响，让后面的逐向量标量量化更有效利用可用数值区间。LVQ 不需要 PCA 旋转、维度分段或 PQ 的多套 k-means 子码本。')
d.sub('三、步骤 2：为每个向量选择范围并编码')
d.eq(r'a_x=\min_j r_{x,j},\quad b_x=\max_j r_{x,j},\quad\Delta_x=\frac{b_x-a_x}{2^{B_1}-1}.')
d.eq(r'k_{x,j}=\operatorname{clip}\!\left(\operatorname{round}\frac{r_{x,j}-a_x}{\Delta_x},0,2^{B_1}-1\right),\quad\widetilde r_{x,j}=a_x+\Delta_xk_{x,j}.')
d.p('以上写法适用于非零范围；常量向量需用退化分支处理。输出是 B₁-bit 标签和两个范围常数（也可以等价表示成尺度与偏移）。不同向量独立使用整个整数区间，避免共享全局范围被少数大值支配。原论文通常以低精度保存范围常数，并可按缓存行粒度补齐。')
d.p('教学例子：B₁=4、范围 [−1,2] 时，步长为 0.2；坐标 0.34 编码为 7、重建为 0.4。若另一个向量范围缩为 [−0.1,0.2]，步长变为 0.02。自适应来自每个向量的尺度，不来自标签位宽变化。')
d.sub('四、步骤 3：可选地编码一级重建残差')
d.eq(r'e_x=r_x-\widetilde r_x,\qquad\widetilde x^{(1)}=c+\widetilde r_x,\qquad\widetilde x^{(2)}=c+\widetilde r_x+\widehat e_x.')
d.p('理想最近舍入时，一级残差每坐标位于约 [−Δₓ/2,Δₓ/2]。论文用 B₂ bit 在这个由一级步长确定的范围内再做标量量化，因此第二级不必另存一套逐向量范围常数。这里讲的是编码范围；不能由此断言真实量化误差在所有数据上严格均匀或独立。')
d.p('输出是一对码，记为 LVQ-B₁×B₂。遍历时只读一级；候选确定后才取得二级码并提升距离精度。总码量增加约 DB₂ bit，另计一级常数和对齐；这不会变成“免费”的精度补偿。')
d.sub('五、步骤 4：压缩向量怎样参与图构建')
d.p('论文采用 Vamana 式图：以每个点为 query 搜索邻居候选，排序并剪枝，加入反向边且限制出度。可以用 LVQ 压缩表示完成这些距离计算，以降低构建时的向量内存与访存量。论文分析了量化误差对图剪枝等步骤的影响，并用实验验证低比特构图的实用性。')
d.p('构图中的两端都来自数据库，而在线 query 可以保持浮点，因此距离计算端点不同。压缩构图有效的证据并不等于任何 bit 数、任何分布下都生成完全相同的图。')
d.sub('六、步骤 5：索引存储与在线距离')
d.table(['对象','论文中的用途'],[('共享均值','编码与查询使用相同中心'),('一级标签及范围常数','支撑建图和图遍历'),('可选二级残差标签','仅对最终候选精细重排'),('邻接表与入口','决定搜索路径'),('候选池/访问标记','query 工作区')])
d.eq(r'\widehat d_1^2(q,x)=\sum_j\left[(q_j-c_j)-(a_x+\Delta_xk_{x,j})\right]^2.')
d.p('query 保持浮点；码可在距离内核中按需解码，不必预先解压全库。分数是到重建向量的 L2；它没有 SAQ 式“保存真实模长、只修正交叉项”的比值结构。原论文还用向量化与数据排列改善解码和内存访问。')
d.sub('七、步骤 6：图遍历与双层重排')
d.p('从入口开始，以一级近似距离维护最多 W 个候选，每次展开最近的未处理节点并评估邻居，直到没有待展开候选。单层版本直接根据一级分数返回。双层版本取回最终候选的残差码，以两层重建重新排序：')
d.eq(r'\widehat d_2^2(q,x)=\|q-(c+\widetilde r_x+\widehat e_x)\|^2.')
d.p('二级码改善的是候选集合内的距离，不会重新搜索已经因一级分数和有限池而遗漏的区域。W 是搜索宽度，也不是两级 bit 数或图出度。')
d.sub('八、从误差看方法边界')
d.eq(r'\epsilon_x=\widetilde x-x,\qquad\widehat d^2-d^2=-2(q-x)^\top\epsilon_x+\|\epsilon_x\|^2.')
d.p('逐向量范围更充分地利用 bit，但单向量中的极端坐标仍能拉大步长。加入二级后，误差中的 ε 换成两层重建误差；重建更准一般有利于排序，却不保证有限图搜索的 recall 单调提高。还需考虑低精度范围常数带来的附加误差。')
d.source('原论文 §2—5','Similarity search in the blink of an eye with compressed indices','https://www.vldb.org/pvldb/vol16/p3433-aguerrebere.pdf')
d.part('第二部分：我们的磁盘实验改了什么')
d.p('项目名 OG-LVQ 对应 SVS Vamana + 单层 LVQ4，不启用论文的二级残差重排。官方 SVS 建图/保存的图行和码行转换成 graph.pages、lvq4.pages，按 4 KiB 打包；中心常驻，图和码按需读取并共享 query 内页缓存。')
storage(d)
d.p('实际顺序：读取入口 LVQ 行 → 一级评分入池 → 选 u 并读取图行 → 对新邻居逐个读取 LVQ 行、评分入池 → 按 LVQ4 分数返回 top-10。磁盘行保留 Turbo 排列，末尾有两个 float32 的 scale/bias 和一个中心 selector。')
d.p('查询端采用兼容 SVS 保存布局的本地解码距离和搜索循环；它并非直接调用原封不动的官方 SIMD kernel。内存/磁盘 top-10 parity 脚本用于检验行为一致性；本次不重新运行。')
d.source('实现定位','experiments/05_disk_system_fair/native/og_lvq_disk_port.cpp；tests/run_og_lvq_disk_port_parity.py。用户提供的 LVQ.pdf 实为 LOPQ，本篇依据上列正确 LVQ 论文。');d.save()

# NSG
d=intro('05_glass_nsg');d.part('第一部分：论文中的 NSG 方法')
d.sub('一、先看全流程与符号')
d.p('NSG（Navigating Spreading-out Graph）的论文主线是构建一个稀疏、可达且便于贪心导航的图：先用近似 kNN 图发现候选，再以几何规则选边，最后修复入口到全图的可达性。Glass 是实现库，SQ4U 是我们选用的量化后端；两者的具体组合放在第二部分，不当作 NSG 原论文的编码方法。')
d.table(['符号','类型 / 含义'],[('xᵤ,q∈Rᴰ','节点向量与 query'),('Gknn,GNSG','初始近似 kNN 图与最终 NSG'),('s；R；L','导航入口；目标出度预算；候选池宽度'),('Cᵤ,Nᵤ','u 的候选邻居集合与已选邻居集合'),('δ(u,v)=‖xᵤ−xᵥ‖','原空间欧氏距离')])
d.fig('论文方法：候选发现、几何选边与可达性修复',[('初始近似 kNN 图','为候选搜索提供连接\n尚不是最终 NSG'),('确定导航入口','计算数据中心\n搜索其附近数据库节点'),('为每点搜索候选','入口出发搜索该点\n合并访问点与原邻居'),('几何剪枝选边','按距当前点远近处理\n保留有方向差异的邻居'),('修复入口可达性','DFS 检查未覆盖节点\n添加连接并继续检查'),('原空间图查询','有限池内贪心展开\n按距离更新并返回 top-k')], 'NSG 原论文没有本文实验里的 SQ4U 双端量化；相关变化全部放到第二部分。')
d.sub('二、步骤 1：建立初始近似 kNN 图')
d.p('输入是原始向量集合。首先用现成近似近邻方法建立 kNN 图，供后续候选发现。这里 kNN 图的作用是提供足够丰富的局部连接；最终 NSG 并不简单照抄全部 kNN 边，而是重新筛选连接，兼顾搜索路径与索引大小。')
d.p('与 SAQ 的训练/编码步骤对应，NSG 这一阶段学习的是图连接关系。论文没有要求减均值后量化、PCA 分段或为每点生成低比特码；原向量用于后续距离计算。')
d.sub('三、步骤 2：选一个导航入口')
d.eq(r'c=\frac1N\sum_ux_u,\qquad s\approx\arg\min_u\|x_u-c\|_2.')
d.p('计算数据中心 c，在初始图上以 c 为 query 搜索，返回接近中心的数据库节点作为 navigating node。入口必须是图中的节点，不能直接把均值向量当作一个天然存在的节点。这里 c 只用于找入口，不是量化参考中心。')
d.sub('四、步骤 3：为每个节点收集候选邻居')
d.p('对每个节点 u，以 xᵤ 为 query、从导航入口 s 出发在初始图上搜索。收集搜索期间访问的节点，并与 u 的原 kNN 邻居合并，构成 Cᵤ。这样候选不仅包含局部近邻，还包含从入口接近 u 的路径上的点，有机会保留有用的导航连接。')
d.p('输出是每个节点的候选集合及距离。候选搜索仍是有限宽近似过程，因此它是对理论图结构的实用近似，不是枚举全部点对。')
d.sub('五、步骤 4：用几何剪枝保留方向差异')
d.p('按距 u 从近到远处理候选。先保留近邻；当更远候选 v 已被某个已选邻居 w 覆盖时，不再加 u→v。MRNG 启发的典型距离比较可以写成：')
d.eq(r'\exists w\in N_u:\quad\delta(w,v)<\delta(u,v),\qquad\delta(u,w)\le\delta(u,v).')
d.p('第二个条件由处理顺序提供；第一个条件表示已有 w 更靠近 v。直观上，保留到 w 的边可能已经给出了通往 v 所在方向的中继，所以不必把同一方向的近点全部直连。实际构图还受候选集合、出度预算和并列距离规则约束。')
d.p('论文先分析具备单调搜索性质的 MRNG，再构造更便宜的近似 NSG。不要把理论 MRNG 的性质不加条件地转述成任何 NSG 实例必然无漏检。')
d.sub('六、步骤 5：修复从入口出发的可达性')
d.p('局部选边后，不能仅凭每个节点都有邻居就认为从 s 可以到达全图。论文从 s 做深度优先遍历，检查未覆盖的节点，并添加连接以扩展覆盖范围，继续直到所有节点可从入口到达。这里解决的是有向图的入口可达性。')
d.p('可达性是搜索的必要结构基础，但查询只展开有限节点时，仍可能错过近邻。它不是“扩大搜索预算以前，就能精确访问所有需要的点”的承诺。')
d.sub('七、步骤 6：索引存储与查询')
d.table(['对象','论文中的用途'],[('原向量','计算 query 与候选的真实距离'),('稀疏邻接表','决定图上可以走向哪些节点'),('导航入口','每次搜索的起点'),('有限宽候选池与访问标记','控制扩展顺序与工作量')])
d.eq(r'd^2(q,x_v)=\sum_{j=1}^{D}(q_j-x_{v,j})^2.')
d.p('查询从入口开始，按距离维护最多 L 个候选，反复展开最近的未处理节点，评估其邻居并更新候选池。没有可继续处理的候选后，从保留的近候选中选 top-k。增大 L 通常增加访问范围与距离计算量。使用平方 L2 排序与欧氏距离一致。')
d.sub('八、从误差看方法边界')
d.p('按原始浮点距离查询时，没有本文 SQ4U 所带来的量化误差；主要近似来自图构建和有限预算遍历。MRNG 理论、NSG 实际图、实现库的优化与后续量化版本应分别判断。稀疏图减少邻居评估工作，但过少连接也可能延长路径；内存优势不能自动外推为磁盘 I/O 优势。')
d.source('原论文，NSG 构图与 Algorithm 2','Fast Approximate Nearest Neighbor Search with the Navigating Spreading-out Graph','https://arxiv.org/abs/1707.00143v9')
d.part('第二部分：我们的磁盘实验改了什么')
d.p('我们采用 Glass 的 NSG_R64_L400_SQ4U。图由官方 builder 构建，距离后端选用共享标量范围的 SQ4U；数据库和 query 都被量化为 4 bit，再调用 u4×u4 整数 L2 内核。这是所选实现配置，不是 NSG 原论文的量化步骤。')
d.eq(r'k_j(x)=\operatorname{round}\!\left(15\operatorname{clip}\left(\frac{x_j-a}{b-a},0,1\right)\right),\quad s(q,x)=\sum_j[k_j(q)-k_j(x)]^2.')
d.p('非退化范围下，共享步长 Δ=(b−a)/15；Δ²s 是双端重建空间的平方 L2。min/dif 来自共享校准，保留官方截断和对齐规则。图行与码行分别写入 graph.pages、sq4u_codes.pages，用 O_DIRECT/libaio 按 4 KiB 读取。')
storage(d)
d.p('实际顺序：编码 query → 读取入口码并评分 → 选 u 读取图行 → 对尚未 seen 的邻居读取 SQ4U 码并评分入池 → 按整数分数返回 top-10，无 FP32 最终重排。查询级页缓存复用图页/码页；控制流为本地磁盘循环。误差由图搜索与双端量化共同决定。')
d.source('实现定位','experiments/05_disk_system_fair/native/glass_disk_port.cpp；baselines/pyglass/glass/quant/sq4u_quant.hpp、calibrator.hpp。');d.save()
print('Rebuilt four baseline documents; Ours and manifest preserved.')
