"""Render this manuscript's deliberately small Markdown subset to ACM LaTeX.

No network or third-party packages. Run after editing manuscript.md.
This checks conversion structure; it is not a substitute for TeX compilation.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent


def escape(text):
    mapping = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%",
               "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{",
               "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
               "–": "--", "—": "---", "‘": "`", "’": "'",
               "“": "``", "”": "''"}
    return "".join(mapping.get(c, c) for c in text)


def inline(text):
    pattern = r"(\$[^$]+\$|\[@[^\]]+\]|\*\*.+?\*\*|`[^`]+`|\[[^\]]+\]\(https?://[^)]+\))"
    out = []
    for part in re.split(pattern, text):
        if part.startswith("$") and part.endswith("$"):
            out.append(part)
        elif part.startswith("[@"):
            out.append(r"\cite{" + ",".join(re.findall(r"@([\w-]+)", part)) + "}")
        elif part.startswith("**"):
            out.append(r"\textbf{" + inline(part[2:-2]) + "}")
        elif part.startswith("`"):
            out.append(r"\texttt{" + escape(part[1:-1]) + "}")
        elif re.match(r"\[.+\]\(https?://", part):
            label, url = re.match(r"\[(.+)\]\((.+)\)", part).groups()
            out.append(r"\href{" + url + "}{" + escape(label) + "}")
        else:
            out.append(escape(part))
    return "".join(out)


def render(lines):
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        if re.fullmatch(r"<!-- diskfigure: fig[0-9]+_[a-z_]+ -->", line):
            name = line.split(": ", 1)[1].split(" -->", 1)[0]
            out.append(r"\diskfigure{" + name + "}")
            i += 1
        elif not line.strip() or line.startswith("<!--"):
            out.append("")
            i += 1
        elif line == "$$":
            j = lines.index("$$", i + 1)
            math = "\n".join(lines[i+1:j])
            # Separate independent equalities where the author used wide spacing.
            math = math.replace(r",\qquad", r",\\").replace(r",\quad", r",\\")
            out.append("\\begin{equation}\n\\begin{gathered}\n" + math +
                       "\n\\end{gathered}\n\\end{equation}")
            i = j + 1
        elif line.startswith("```"):
            j = next(j for j in range(i+1, len(lines)) if lines[j].startswith("```"))
            out.append("\\begin{lstlisting}\n" + "\n".join(lines[i+1:j]) + "\n\\end{lstlisting}")
            i = j + 1
        elif line.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                row = [s.strip() for s in lines[i].strip("|").split("|")]
                if not all(re.fullmatch(r"[-: ]+", s) for s in row):
                    rows.append(row)
                i += 1
            columns = len(rows[0])
            assert all(len(row) == columns for row in rows)
            spec = " ".join([r">{\raggedright\arraybackslash}X"] * columns)
            out.append(r"\par\medskip\noindent\begin{tabularx}{\columnwidth}{" + spec + "}\n\\toprule")
            for n, row in enumerate(rows):
                out.append(" & ".join(inline(cell) for cell in row) + r" \\")
                if n == 0:
                    out.append(r"\midrule")
            out.append("\\bottomrule\n\\end{tabularx}\n\\par\\medskip")
        elif line.startswith("### "):
            heading = re.sub(r"^\d+(?:\.\d+)*\s+", "", line[4:])
            out.append(r"\subsection{" + inline(heading) + "}")
            i += 1
        elif line.startswith("## "):
            heading = re.sub(r"^\d+(?:\.\d+)*\s+", "", line[3:])
            if heading == "References":
                break
            out.append(r"\section{" + inline(heading) + "}")
            if heading == "ExRaBitQ-Disk":
                out.append(r"\input{overview}")
            i += 1
        elif line.startswith("- "):
            out.append(r"\begin{itemize}")
            while i < len(lines) and lines[i].startswith("- "):
                out.append(r"\item " + inline(lines[i][2:]))
                i += 1
            out.append(r"\end{itemize}")
        else:
            out.append(inline(line))
            i += 1
    return "\n".join(out)


def main():
    text = (ROOT / "manuscript.md").read_text()
    title = text.splitlines()[0][2:]
    abstract = text.split("## Abstract\n", 1)[1].split("\n## 1 Introduction", 1)[0].strip()
    body = "## 1 Introduction" + text.split("\n## 1 Introduction", 1)[1]
    (ROOT / "body.tex").write_text("% Generated by render_latex.py; edit manuscript.md.\n" + render(body.splitlines()) + "\n")
    main_tex = r"""% Generated by render_latex.py. Draft with explicit evidence placeholders.
\documentclass[sigconf,anonymous]{acmart}
\usepackage{amsmath,booktabs,tabularx,array,listings,tikz}
\usetikzlibrary{arrows.meta,positioning}
\setlength{\emergencystretch}{1em}
\setcopyright{none}
\settopmatter{printacmref=false}
\acmDOI{}
\acmISBN{}
\acmConference[SIGMOD submission draft]{}{}{}
\lstset{basicstyle=\ttfamily\small,breaklines=true,columns=fullflexible,keepspaces=true,frame=single}
\title{TITLE}
\begin{document}
\begin{abstract}
ABSTRACT
\end{abstract}
\keywords{Approximate nearest neighbor search, vector quantization, graph indexes, disk I/O}
\maketitle
\newcommand{\diskfigure}[1]{\input{figures/disk_w32/#1.tex}}
\input{body}
\bibliographystyle{ACM-Reference-Format}
\bibliography{references}
\end{document}
"""
    (ROOT / "main.tex").write_text(main_tex.replace("TITLE", inline(title)).replace("ABSTRACT", inline(abstract)))
    print("Rendered main.tex and body.tex")


if __name__ == "__main__":
    main()
